import {DiscordSDK} from '@discord/embedded-app-sdk';
import './style.css';
import {LivePlayer} from './live-player.js';
const $=s=>document.querySelector(s);
let token,user,ws,room,sdk,config,state={},lastFrame=0,auto=false,toastTimer,joining=false,roomsSignature,streamActive=false;
const notify=text=>{$('#message').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#message').textContent='',8000);};
const player=new LivePlayer($('#live-screen'),notify);
player.onFrame=()=>{showMedia();};
function showMedia(){const pc=controlling();$('#live-screen').hidden=!streamActive||pc;$('#screen').hidden=!(lastFrame&&(!streamActive||pc));$('#empty').hidden=!!(streamActive||lastFrame);}
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
const send=m=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(m));};
const controlling=()=>state.controller?.id===user?.id && state.until>Date.now() && lastFrame>Date.now()-5000;
function render(){const yes=controlling();$('#stage').classList.toggle('controlling',yes);document.querySelectorAll('[data-control]').forEach(b=>b.disabled=!yes);$('#request').disabled=!state.host||!!state.controller||state.pending;$('#release').hidden=state.controller?.id!==user?.id;$('#request').hidden=!$('#release').hidden;$('#control-title').textContent=state.controller?(yes?'You have the controls.':`${state.controller.username} has control`):(state.pending?'Waiting for host approval…':'Ask, then take the wheel.');$('#status').textContent=state.streaming?'● Browser screen live':state.host?'● Companion preview':'Waiting for host to share';$('#members').textContent=`${state.members||1} in the room`;$('#room-title').textContent=state.creator?`${state.creator}’s room`:'Your room';$('#freshness').textContent=controlling()?'PC control preview':streamActive?(player.lastFrame>Date.now()-5000?'Live video · target 30 FPS':'Waiting for video…'):lastFrame>Date.now()-5000?'Companion preview':'Offline';$('#host-file').disabled=!!state.host;$('#host-help').textContent=state.browserHost?'Your browser host page is open. Choose Share screen there to start.':'Open the browser host page and choose a tab, window, or screen. No download needed.';$('#browser-host').disabled=!!state.browserHost;$('#stop-browser').hidden=!state.streaming;showMedia();if(!yes){auto=false;$('#auto').textContent='Start auto-scroll';}}
function input(m){if(controlling())send({type:'input',...m});else notify('Request control first, and wait for a live preview.');}
async function refreshRooms(){if(!token||room||joining)return;try{const data=await api('rooms');if(room||joining)return;const signature=JSON.stringify(data.rooms);if(signature===roomsSignature)return;roomsSignature=signature;const list=$('#room-list');list.replaceChildren();if(!data.rooms.length){const p=document.createElement('p');p.textContent='No rooms yet. Host one and your friends can join here.';list.append(p);}for(const r of data.rooms){const card=document.createElement('div');card.className='room-tile';const title=document.createElement('h3');title.textContent=`${r.creator}’s room`;const desc=document.createElement('p');desc.textContent=`${r.host?'● Sharing now':'Setting up screen'} · ${r.members}/12 people`;const button=document.createElement('button');button.textContent=r.full?'Room full':'Join room';button.disabled=r.full;button.onclick=()=>connect(r.code);card.append(title,desc,button);list.append(card);}}catch(e){notify(e.message);}}
function clearPreview(){streamActive=false;player.stop();$('#sound').hidden=true;lastFrame=0;$('#screen').removeAttribute('src');$('#screen').hidden=true;$('#empty').hidden=false;}
async function exitFullscreen(){if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});$('#stage').classList.remove('expanded');document.body.classList.remove('screen-expanded');$('#exit-fullscreen').hidden=true;}
function lobby(){room=null;joining=false;state={};clearPreview();exitFullscreen();$('#lobby').hidden=false;$('#room').hidden=true;$('#create').disabled=!token;render();refreshRooms();}
function connect(code){if(joining||room)return;joining=true;$('#create').disabled=true;const connection=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`);ws=connection;connection.binaryType='arraybuffer';connection.onopen=()=>connection.send(JSON.stringify({type:'join',token,room:code}));connection.onmessage=e=>{if(ws!==connection)return;if(typeof e.data!=='string'){player.receive(e.data);return;}const m=JSON.parse(e.data);if(m.type==='stream-start'){streamActive=true;player.start(m);$('#sound').hidden=!m.audio;showMedia();}if(m.type==='stream-stop'){streamActive=false;player.stop();$('#sound').hidden=true;showMedia();}if(m.type==='joined'){joining=false;room=code;$('#lobby').hidden=true;$('#room').hidden=false;$('#host-tools').hidden=!m.owner;$('#pairing').hidden=true;}if(m.type==='state'){state=m;render();}if(m.type==='frame'){$('#screen').src='data:image/jpeg;base64,'+m.jpeg;lastFrame=Date.now();render();}if(m.type==='clear'){lastFrame=0;$('#screen').removeAttribute('src');render();}if(m.type==='notice')notify(m.message);};connection.onclose=e=>{if(ws!==connection)return;ws=null;lobby();notify(e.reason||'Disconnected. You can join again from the room list.');};connection.onerror=()=>notify('Connection failed. Check your internet connection.');}
$('#create').onclick=async()=>{if(joining||room)return;$('#create').disabled=true;try{connect((await api('rooms',{})).code);}catch(e){$('#create').disabled=false;notify(e.message);}};
$('#refresh').onclick=refreshRooms;
async function external(url){if(sdk)await sdk.commands.openExternalLink({url});else window.open(url,'_blank','noopener');}
$('#browser-host').onclick=async()=>{try{const response=await api('broadcast',{room});await external(response.url);}catch(e){notify(e.message);}};
$('#stop-browser').onclick=()=>send({type:'stop-browser'});
$('#download-companion').onclick=async()=>{try{const origin=config?.demo?location.origin:config?.publicOrigin;if(!origin)throw Error('The server download address is not configured.');await external(origin+'/downloads/WATCH-TALIM-Companion.zip');}catch(e){notify(e.message);}};
$('#sound').onclick=async()=>{try{$('#sound').textContent=await player.toggleAudio()?'Mute sound':'Enable sound';}catch{notify('Sound could not start in this client.');}};
$('#leave').onclick=()=>{const previous=ws;ws=null;previous?.close();lobby();};
$('#end-room').onclick=async()=>{try{await api(`rooms/${room}/close`,{});}catch(e){notify(e.message);}};
$('#pair').onclick=async()=>{try{const p=await api('pair',{room});$('#pair-code').textContent=p.code;$('#pairing').hidden=false;}catch(e){notify(e.message);}};
$('#host-file').onclick=async()=>{try{const p=await api('pair',{room});const origin=config.demo?location.origin:config.publicOrigin;if(!origin)throw Error('Host file needs a public server address. Use Manual pairing for now.');const url=`${origin}/host-file/${p.download}`;if(sdk){await sdk.commands.openExternalLink({url});}else{const a=document.createElement('a');a.href=url;a.download='WATCH-TALIM-host.talim';document.body.append(a);a.click();a.remove();}notify('Open the downloaded host file in the Windows companion within 2 minutes.');}catch(e){notify(e.message);}};
$('#screen-size').onchange=()=>{document.body.classList.remove('screen-small','screen-large');const size=$('#screen-size').value;if(size!=='medium')document.body.classList.add(`screen-${size}`);};
$('#fullscreen').onclick=async()=>{const stage=$('#stage');$('#exit-fullscreen').hidden=false;try{if(!stage.requestFullscreen)throw Error();await stage.requestFullscreen();}catch{stage.classList.add('expanded');document.body.classList.add('screen-expanded');}};
$('#exit-fullscreen').onclick=e=>{e.stopPropagation();exitFullscreen();};
document.addEventListener('fullscreenchange',()=>{$('#exit-fullscreen').hidden=!document.fullscreenElement&&!$('#stage').classList.contains('expanded');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&($('#stage').classList.contains('expanded')||document.fullscreenElement)){e.preventDefault();e.stopImmediatePropagation();exitFullscreen();}},true);
$('#request').onclick=()=>send({type:'request'});$('#release').onclick=()=>send({type:'release'});$('#stop').onclick=()=>send({type:'stop'});
$('#url-form').onsubmit=e=>{e.preventDefault();input({kind:'open',url:$('#url').value});};
$('#text-form').onsubmit=e=>{e.preventDefault();input({kind:'text',text:$('#text').value});$('#text').value='';};
$('#previous').onclick=()=>input({kind:'key',key:'ArrowUp'});$('#next').onclick=()=>input({kind:'key',key:'ArrowDown'});$('#pause').onclick=()=>input({kind:'key',key:'Space'});
$('#auto').onclick=()=>{if(!controlling())return;auto=!auto;input({kind:'auto',seconds:auto?Number($('#interval').value):0});$('#auto').textContent=auto?'Stop auto-scroll':'Start auto-scroll';};
function click(e,button){if(!controlling())return;const r=$('#screen').getBoundingClientRect();input({kind:'click',x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)),button});$('#stage').focus();}
$('#screen').onclick=e=>click(e,'left');$('#screen').oncontextmenu=e=>{e.preventDefault();click(e,'right');};
let lastScroll=0;$('#stage').addEventListener('wheel',e=>{if(!controlling())return;e.preventDefault();if(Date.now()-lastScroll<100)return;lastScroll=Date.now();input({kind:'scroll',amount:e.deltaY>0?-3:3});},{passive:false});
$('#stage').onkeydown=e=>{if(e.target!==$('#stage')||!controlling()||e.ctrlKey||e.altKey||e.metaKey)return;const keys=['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Enter','Escape','Backspace','Tab','Home','End'];if(e.key===' '||keys.includes(e.key)){e.preventDefault();input({kind:'key',key:e.key===' '?'Space':e.key});}else if(e.key.length===1){e.preventDefault();input({kind:'text',text:e.key});}};
setInterval(render,1000);setInterval(()=>{if(!document.hidden)refreshRooms();},5000);
async function start(){try{config=await api('config');let result;if(config.demo){result=await api('login',{name:`Local guest ${Math.floor(Math.random()*900+100)}`});$('#identity').textContent='LOCAL PREVIEW';}else{if(!config.clientId)throw Error('Server needs Discord application credentials. See START-HERE.md.');sdk=new DiscordSDK(config.clientId);await sdk.ready();const {code}=await sdk.commands.authorize({client_id:config.clientId,response_type:'code',state:'',prompt:'none',scope:['identify']});result=await api('login',{code});await sdk.commands.authenticate({access_token:result.accessToken});$('#identity').textContent=result.user.username;}token=result.token;user=result.user;$('#create').disabled=false;await refreshRooms();}catch(e){notify(e.message);$('#identity').textContent='Setup needed';$('#create').disabled=true;}}
start();
